services:
  voicestreamer:
    build:
      context: ..
      dockerfile: VoiceStreamer/Dockerfile
    env_file:
    - .env
    - path: .env.prod
      required: false    
    volumes:
      - voice:/app/data
    restart: unless-stopped
    
    container_name: voicestreamer

volumes:
  voice: